name: external_mic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  miniaudio_dart: ^1.0.10
  record: ^6.2.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/string/
